apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-10-posts-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: last-10-posts-service
  template:
    metadata:
      labels:
        app: last-10-posts-service
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo "Czekam na bazę danych..."; sleep 2; done;']
      containers:
      - name: last-10-posts-container
        image: lw89233/last_10_posts:latest
        ports:
        - containerPort: 8003
        env:
        - name: LAST_10_POSTS_MICROSERVICE_PORT
          value: "8003"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: last-10-posts-service
spec:
  selector:
    app: last-10-posts-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003