apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: lw89233/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: REGISTRATION_MICROSERVICE_HOST
          value: "register-service"
        - name: REGISTRATION_MICROSERVICE_PORT
          value: "8000"
        - name: LOGIN_MICROSERVICE_HOST
          value: "login-service"
        - name: LOGIN_MICROSERVICE_PORT
          value: "8001"
        - name: POSTS_MICROSERVICE_HOST
          value: "posts-service"
        - name: POSTS_MICROSERVICE_PORT
          value: "8002"
        - name: LAST_10_POSTS_MICROSERVICE_HOST
          value: "last-10-posts-service"
        - name: LAST_10_POSTS_MICROSERVICE_PORT
          value: "8003"
        - name: FILE_TRANSFER_MICROSERVICE_HOST
          value: "file-transfer-service"
        - name: FILE_TRANSFER_MICROSERVICE_PORT
          value: "8004"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000